### PR TITLE
fix(dart_frog_cli): nested dynamic route resolution

### LINKED ISSUE #390: fix: nesting multiple dynamic routes creates invalid server.dart in `dart_frog_cli` 0.2.1
Credit to @bruceclark406 who reported the issue to me :)

**Description**

In the latest version of `dart_frog_cli` (`0.2.1`), running `dart_frog build` on routes structured like so

```
routes
  - [test1]
      - [test2].dart
```
Produces an invalid `server.dart`

```dart
Handler build$test1Handler(String test1,) {
  final pipeline = const Pipeline();
  final router = Router()
    ..all('/<test2>', (context,test2,) => $test1_$test2.onRequest(context,test1,,test2,));
  return pipeline.addHandler(router);
}
```

You can see where the handler is called, there are two commas instead of one between `test1` and `test2`

In `dart_frog_cli 0.2.0`, the same folder structure generates

```dart
Handler build$test1Handler(String test1,) {
  final pipeline = const Pipeline();
  final router = Router()
    ..all('/<test2>', (ctx,test2,) => $test1_$test2.onRequest(ctx, test1,test2,));
  return pipeline.addHandler(router);
}
```

Which seems correct

**Steps To Reproduce**

1. Clone this [minimum reproduction](https://github.com/mtwichel/dart_frog_minimum_reproduction) repo
2. Make sure you're using `dart_frog_cli 0.2.1`
3. Run `dart_frog build`
4. Run `dart build/bin/server.dart`
5. See error in console output. You can inspect the `server.dart` file for errors

**Current Workarounds**

For now we have downgraded to `dart_frog_cli 0.2.0` in our CI/CD and local machines

### PR DESCRIPTION
**Pull request by felangel**
## Status

**READY**

## Description

- fix(dart_frog_cli): nested dynamic route resolution (closes #390)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: examples/kitchen_sink/routes/api/_middleware.dart [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import 'dart:io';
+
+import 'package:dart_frog/dart_frog.dart';
+
+Handler middleware(Handler handler) {
+  return (context) {
+    if (!context.request.headers.containsKey('Authorization')) {
```
Comment (wolfenrain) [inline examples/kitchen_sink/routes/api/_middleware.dart:7]: dont we have const values for that?

**Review by wolfenrain — APPROVED** [review]

**Review by wolfenrain — APPROVED** [review]
