### PR TITLE
fix: use custom docker file when building prod server

### LINKED ISSUE #569: fix: Dockerfile is not inherited during build production
**Description**

If you add a Dockerfile to the project folder and change it, a clean Dockerfile will be generated in the build folder

**Steps To Reproduce**

1. Create new dart_frog project (dart_frog create test)
2. Create new Dockerfile in root folder 
3. Edit Dockerfile in root folder 
4. Create production build (dart_frog build)

**Expected Behavior**

I expected that Dockerfile would be copied from the root folder , and not create a new Dockerfile

### PR DESCRIPTION
**Pull request by erickzanardo**
## Status

**READY**

## Description

Changes the pre_gen so it will check if there is a custom Dockerfile, and when one is present, uses it instead of generating one.

Fixes #569

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: bricks/dart_frog_prod_server/hooks/pre_gen.dart [hunk 1]
```diff
@@ -1,9 +1,11 @@
 import 'dart:async';
 import 'dart:io' as io;
```
Comment (renancaraujo) [inline bricks/dart_frog_prod_server/hooks/pre_gen.dart:2]: Duplicated import

**Review by renancaraujo — APPROVED** [review]

File: bricks/dart_frog_prod_server/hooks/pre_gen.dart (hunk 1 above)
Comment (erickzanardo) [reply bricks/dart_frog_prod_server/hooks/pre_gen.dart]: opsie, fixed

**Review by renancaraujo — APPROVED** [review]
